import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrideFlag from './components/inclusivePrideFlagColors'; // Import the PrideFlag component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TJD Poetry",
  description: "Generated by @tjdpoetry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrideFlag /> {/* Use the PrideFlag component as a background */}
        {children}
      </body>
    </html>
  );
}